- name: check a number less than 20 or not
  hosts: local  
  connection: local
  vars:
    NUMBER_OF_SESSIONS: 7

  tasks:
  - name: Is ansible more than 5 sessions 
    ansible.builtin.debug:
      msg: "Yes, more than 5 sessions" 
    when: NUMBER_OF_SESSIONS > 5 
